package fr.univartois.butinfo.lensymphony.synthesizer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import fr.univartois.butinfo.lensymphony.notes.Note;
import fr.univartois.butinfo.lensymphony.notes.NotePitch;
import fr.univartois.butinfo.lensymphony.notes.NoteValue;
import fr.univartois.butinfo.lensymphony.notes.SimpleNoteFactory;
import fr.univartois.butinfo.lensymphony.notes.PitchClass;

/**
 * Unit tests for the {@link TimbaleSynthesizer} class.
 * <p>
 * These tests ensure that the timpani (kettle drum) synthesizer behaves correctly by:
 * <ul>
 *   <li>Generating valid, non-null sound data for valid notes.</li>
 *   <li>Producing silent (zero-filled) output for zero-frequency notes.</li>
 *   <li>Exhibiting a realistic amplitude decay over time (sound fades naturally).</li>
 *   <li>Handling edge cases such as zero or negative duration properly.</li>
 * </ul>
 * </p>
 *
 * <p>Each test uses a simple note generated by the {@link SimpleNoteFactory}
 * and analyzes the resulting waveform samples.</p>
 *
 * @author 
 * (tibot duquesne)
 * @version 1.0
 */
public class TimbaleSynthesizerTest {

    /**
     * Tests that the synthesizer generates valid, non-empty sample data
     * for a normal note.
     */
    @Test
    void testValidSynthesis() {
        NotePitch pitch = NotePitch.of(PitchClass.C, 3);
        NoteValue value = NoteValue.QUARTER;
        Note note = SimpleNoteFactory.getInstance().createNote(pitch, value);

        TimbaleSynthesizer synth = TimbaleSynthesizer.getInstance();
        double[] samples = synth.synthesize(note, 120, 1.0);

        assertNotNull(samples, "Samples array should not be null.");
        assertTrue(samples.length > 0, "Samples array should not be empty.");
    }

    /**
     * Tests that the synthesizer produces a silent waveform when the note
     * frequency is zero.
     */
    /**
     * Tests that the synthesizer produces a silent waveform when the note
     * frequency is zero.
     */
    @Test
    void testZeroFrequencyProducesSilence() {
        // Create an anonymous Note that has frequency = 0 and a valid duration.
        Note silentNote = new Note() {
            @Override
            public double getFrequency() {
                return 0.0;
            }

            @Override
            public int getDuration(int tempo) {
                return 500; // 500 ms, for example
            }
        };

        TimbaleSynthesizer synth = TimbaleSynthesizer.getInstance();
        double[] samples = synth.synthesize(silentNote, 120, 1.0);

        assertNotNull(samples, "Samples array should not be null.");
        assertTrue(samples.length > 0, "Samples array should not be empty.");
        for (double sample : samples) {
            assertEquals(0.0, sample, 1e-9, "All samples should be zero for a silent note.");
        }
    }


    /**
     * Tests that the amplitude decays over time, simulating the natural damping
     * of a timpani sound.
     */
    @Test
    void testAmplitudeDecayOverTime() {
        NotePitch pitch = NotePitch.of(PitchClass.D, 3);
        NoteValue value = NoteValue.HALF;
        Note note = SimpleNoteFactory.getInstance().createNote(pitch, value);

        TimbaleSynthesizer synth = TimbaleSynthesizer.getInstance();
        double[] samples = synth.synthesize(note, 100, 1.0);

        assertNotNull(samples);
        assertTrue(samples.length > 0);

        double start = Math.abs(samples[samples.length / 10]);
        double middle = Math.abs(samples[samples.length / 2]);
        double end = Math.abs(samples[samples.length - 1]);

        assertTrue(start >= middle * 0.9, "Amplitude should start strong.");
        assertTrue(middle > end, "Amplitude should decay over time.");
    }

    /**
     * Tests that when the note duration is zero or negative,
     * an empty array is returned.
     */
    @Test
    void testInvalidDurationReturnsEmptyArray() {
        Note note = new Note() {
            @Override
            public double getFrequency() {
                return 440.0;
            }

            @Override
            public int getDuration(int tempo) {
                return 0; // Invalid duration
            }
        };

        TimbaleSynthesizer synth = TimbaleSynthesizer.getInstance();
        double[] samples = synth.synthesize(note, 120, 1.0);

        assertNotNull(samples, "Samples array should not be null.");
        assertEquals(0, samples.length, "Samples array should be empty for zero duration.");
    }
}
